const restaurantList = [
  {
    name: "restaurant1",
    description: "this is a nice restaurant",
    imgSrc: "/assets/fastfood.jpg",
    imgAlt: "fastfood",
    starRating: ".125",
    foodPrice: "1",
  },
  {
    name: "restaurant2",
    description: "this is a nice restaurant",
    imgSrc: "/assets/italien.jpg",
    imgAlt: "italianfood",
    starRating: ".125",
    foodPrice: "2",
  },
  {
    name: "restaurant3",
    description: "this is a nice restaurant",
    imgSrc: "assets/steakhouse.jpg",
    imgAlt: "meatfood",
    starRating: ".850",
    foodPrice: "3",
  },
  {
    name: "restaurant4",
    description: "this is a nice restaurant",
    imgSrc: "assets/veggie.jpg",
    imgAlt: "veggie",
    starRating: ".500",
    foodPrice: "3",
  },
  {
    name: "restaurant5",
    description: "this is a nice restaurant",
    imgSrc: "assets/powke.jpg",
    imgAlt: "poke",
    starRating: ".620",
    foodPrice: "3",
  },
  {
    name: "restaurant6",
    description: "this is a nice restaurant",
    imgSrc: "assets/spaghetti.jpg",
    imgAlt: "spaghetti",
    starRating: ".375",
    foodPrice: "3",
  },
];
